name: smart_calculator
description: A full-featured calculator app with scientific calculations, unit conversion, and OCR capabilities.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  math_expressions: ^2.3.1
  google_ml_kit: ^0.15.0
  speech_to_text: ^6.5.1
  http: ^1.1.0
  shared_preferences: ^2.2.0
  flutter_adaptive_scaffold: ^0.1.0
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 